### ISSUE TITLE
Showing No Results on Android 11

### ISSUE THREAD

**Issue by muazAndroid** [speedchecker/speedchecker-sdk-android#1]
Hello!
I am using the free version of this SDK. All the permissions are granted but no results are shown on Android 11. Kindly share the solution.  Thank You!

**Comment by DenysYakubets** [comment]
Hello,
Thanks for your request. Yes, we already have a task in the backlog to
update a demo version on GitHub. Temporary you can fix the "Android 11"
issue on your side. You need manually ask for location permissions.

You need to request:


*ACCESS_COARSE_LOCATIONACCESS_FINE_LOCATIONACCESS_BACKGROUND_LOCATION*

After that, you will have the opportunity to use our SDK even on Android
11.

Have a nice day!
Regards, Denys.

**Comment by muazAndroid** [comment]
Hello DenysYakubets! I have done manual permissions on Android 11. after that it gives me this error:  onTestFatalError: getDataNetworkTypeForSubscriber

**Comment by DenysYakubets** [comment]
I discussed this request with the project manager and we agreed to update the SDK faster. So, I think today/tomorrow you will get the latest SDK build.

**Comment by muazAndroid** [comment]
Thank You!

**Comment by DenysYakubets** [comment]
The new SDK is ready!

`implementation 'com.speedchecker:android-sdk:4.2.115-demo'`

Please, let me k now if you will have any issues.
