### ISSUE TITLE
Can't import dependencies

### ISSUE THREAD

**Issue by Quinlancpo** [speedchecker/speedchecker-sdk-android#10]

**Comment by Quinlancpo** [comment]
Failed to resolve: com.speedchecker:android-sdk:4.2.151-demo

**Comment by DenysYakubets** [comment]
Hello @Quinlancpo, please, provide more information. Thanks!

**Comment by Quinlancpo** [comment]
Failed to resolve: com.speedchecker:android-sdk:4.2.151-demo

Do as you do, Android studio returns me this message.

**Comment by DenysYakubets** [comment]
Looks like you don't have access to the repository. Please, check if you are using the correct credentials? 

```
maven {
  url 'https://maven.speedcheckerapi.com/artifactory/libs-demo'
  credentials {
      username = "demo"
      password = "AP85qiz6wYEsCttWU2ZckEWSwJKuA6mSYcizEY"
  }
```

**Comment by Quinlancpo** [comment]
Thanks, that is ok!!!
