### ISSUE TITLE
Unsafe implementation of the HostnameVerifier interface

### ISSUE THREAD

**Issue by cwdev19** [speedchecker/speedchecker-sdk-android#2]
Play Console is currently removing applications that are using the above mentioned. This will make this SDK unusable. 

For more information, please check:
https://support.google.com/faqs/answer/7188426

**Comment by DenysYakubets** [comment]
Hello @cwdev19, I updated the SDK. Please, use the latest version this should fix this problem.

`implementation 'com.speedchecker:android-sdk:4.2.115-demo'`
