### ISSUE TITLE
The Crashlytics build ID is missing

### ISSUE THREAD

**Issue by derrickward** [speedchecker/speedchecker-sdk-android#3]
Receive The Crashlytics build ID is missing when my app calls FirebaseApp.initializeApp after adding this library's gradle refrences (no calls to sdk).

**Comment by DenysYakubets** [comment]
Hello @derrickward, we will add this and other issues from GitHub to the next company "sprint" (in 1 week). I will leave this issue open here.

**Comment by DenysYakubets** [comment]
@derrickward please, check if the new SDK build is working for you properly. 

Please, update the SDK:
`implementation 'com.speedchecker:android-sdk:4.2.118-demo-2'`
