### ISSUE TITLE
ACCESS_BACKGROUND_LOCATION in Manifest will cause app to be Rejected

### ISSUE THREAD

**Issue by cwdev19** [speedchecker/speedchecker-sdk-android#4]
Apps will need to follow the below (quoted from the following link):
1. You should never request location permissions from users for the sole purpose of advertising or analytics.
2. Background location may only be used to provide features beneficial to the user and relevant to the core functionality of the app.
https://support.google.com/googleplay/android-developer/answer/9799150?hl=en#zippy=%2Cstep-review-best-practices-for-accessing-location

Forcing users to choose "allow all the time" for location access in this case seems to oppose the above mentioned practice. 

I wish to check with the devs whether we can remove forcing users to accept location access in the background (has to be removed from Manifest too); and allow users to pick the "Allow only while using the app" option.

**Comment by DenysYakubets** [comment]
Hello @cwdev19, location permissions are required for the "Free" plan. You can use "Basic" or "Advance" plans to get flexible SDK and customize this and other parts. Please, check the License section and contact us to get more details. 

Regards, Denys.
