### ISSUE TITLE
Class duplication occurred while adding admob dependency

### ISSUE THREAD

**Issue by muazAndroid** [speedchecker/speedchecker-sdk-android#5]
Hello!
I am facing this error when I try to add Google Admob dependency:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.gms.internal.measurement.zzu found in modules jetified-firebase-analytics-impl-16.2.4-runtime (com.google.firebase:firebase-analytics-impl:16.2.4) and jetified-play-services-measurement-base-18.0.0-runtime (com.google.android.gms:play-services-measurement-base:18.0.0)
     Duplicate class com.google.android.gms.internal.measurement.zzv found in modules jetified-firebase-analytics-impl-16.2

This is because of the SDK's usage of Firebase crashlytics.

**Comment by DenysYakubets** [comment]
Hello @muazAndroid, we will add this and other issues from GitHub to the next company "sprint" (in 1 week). I will leave this issue open here.

**Comment by muazAndroid** [comment]
Thank You! I want to mention that I am using implementation 'com.google.android.gms:play-services-ads:20.2.0'

**Comment by DenysYakubets** [comment]
@muazAndroid please, check if the new SDK build is working for you properly. 

Please, update the SDK:
`implementation 'com.speedchecker:android-sdk:4.2.118-demo-2'`

**Comment by muazAndroid** [comment]
Yes, It works. Thank you so much again for your help.
