### ISSUE TITLE
SpeedcheckerSDK.SpeedTest.startTest takes an activity

### ISSUE THREAD

**Issue by jmoulton-we** [speedchecker/speedchecker-sdk-android#9]
I'm using the SDK in conjunction with [Hilt](https://developer.android.com/training/dependency-injection/hilt-android) to inject speed checking into my app where needed. But, SpeedcheckerSDK.SpeedTest.startTest takes an Activity parameter which makes it really challenging to inject into certain parts of the app. Using Hilt, it makes it imposable to use any the SDK in any [scope that is scoped above](https://developer.android.com/training/dependency-injection/hilt-android#component-hierarchy) the @ActivityScoped. Leaving out most notably @ViewModelScoped.
If possible, consider using the Application [Context](https://developer.android.com/reference/android/content/Context) at SpeedcheckerSDK.SpeedTest.startTest instead of Activity. That would allow Hilt users to use the SDK in every scope.

Another concern that I have is that [Activities are destroyed during re-configurations](https://developer.android.com/guide/topics/resources/runtime-changes), like rotating the screen. I'm not 100% sure how the SDK is using the Activity, but I fear that a re-configuration mid-test might lead to run time issues that are challenging bugs to fix.

**Comment by DenysYakubets** [comment]
Hello @jmoulton-we, unfortunately, it is a limitation of a Free plan. Our SDK doesn't have any Activity relations in Basic and Advanced plans.

Please, check out our License section here to get more information -> [https://github.com/speedchecker/speedchecker-sdk-android#license](https://github.com/speedchecker/speedchecker-sdk-android#license)

**Comment by DenysYakubets** [comment]
Yes, thanks
